remote_theme: daviddarnes/alembic

navigation_header:
  Home: /
  NDVI_Tax_Rate_Map: /NDVI_Tax_Rates/NDVI_Tax_Rates.html
  Chesapeake_Bay_Nitrates_Map: /Chesapeake_Nitrates_Map/Chesapeake_Nitrates_Map.html
  3D_Agisoft_Map: /3D_Map_AGISOFT/3D_Map_AGISOFT.html
Final_Project: /Final_Project/Final_Project.html
